### PR TITLE
Reset "module" to null to prevent memory leaks

### PR DESCRIPTION
**Pull request by Turbo87**
related to https://github.com/emberjs/ember-qunit/pull/258#issuecomment-291239057

### CODE REVIEW

**Comment by Turbo87** [comment]
CI is apparently failing due to https://github.com/emberjs/ember-mocha/pull/145

**Comment by rwjblue** [comment]
Seems like we are creating `module` eagerly and then cleaning in `after` here, any reason we don't create `module` in the `before`?

**Comment by Turbo87** [comment]
@rwjblue that's legacy code... in the code path for the new API we're doing exactly that

**Comment by Turbo87** [comment]
rebased to fix CI

**Comment by joegaudet** [comment]
Hey,

I'm still seeing a memory leak on older versions of ember (2.11.3) - I setup a vanilla 2.11.3 with two component tests.

The number of containers remaining after the test runs grew proportionally with respect to the number of tests.

I added the following code and it resolved the issue.

```
    after(function() {
      Object.keys(this).forEach(key => {
        this[key] = null;
      });
      module = null;
    });
```

**Pull request merged**
