### PR TITLE
Fix broken context cleanup

### LINKED ISSUE #110: Context is not being reset between test runs
```js
  describe('pretty-color integration test', function() {
    setupComponentTest('pretty-color', {
      integration: true
    });

    it('renders with color', function() {
      this.set('name', 'green');
      this.render(Ember.Handlebars.compile(`{{pretty-color name=name}}`));
      expect(Ember.$.trim(this.$().text())).to.equal('Pretty Color: green');
    });

    it('renders a second time without', function() {
      this.render(Ember.Handlebars.compile(`{{pretty-color name=name}}`));
      expect(Ember.$.trim(this.$().text())).to.equal('Pretty Color:');
    });
  });
```

Expected behavior: the second test should pass since the context on each test is being reset and `name` should be `undefined`.

Actual behavior: the `name` value from the first test bleeds into the second test and results in `Pretty Color: green` instead.

Thanks to @acburdine for figuring this out! (see https://github.com/TryGhost/Ghost-Admin/pull/206#issuecomment-263074763)

This seems to have been introduced by v0.9.x, but it not limited to the new testing API.

### PR DESCRIPTION
**Pull request by Turbo87**
This PR reverts #89 and #91 to fix the context cleanup.

Resolves #110 

/cc @dgeb @rwjblue

### CODE REVIEW

**Comment by Turbo87** [comment]
I've now also added test cases to assert that the context in `beforeEach/afterEach` can be used with `.set()` and `.get()`.

https://github.com/emberjs/ember-mocha/pull/87 mentions:

> This ensures that the contexts in various mocha hooks are the same as the hooks used in unit/integration tests.

but given that the tests above are passing now I don't see how this was broken before #87.

**Comment by Turbo87** [comment]
Since this PR is blocking https://github.com/TryGhost/Ghost-Admin/pull/206 I would like to merge this soonish. I'll merge this in the morning (CET) in case there are no objections.

/cc @acburdine

**Comment by rwjblue** [comment]
As mentioned in the linked issue, the current behavior is actually in line with how mocha actually works. Anything set on `this` is shared amongst tests within a module (feel free to double check this in plain mocha setup without ember-mocha).

**Comment by rwjblue** [comment]
Also, why is this targeting the older branch?

**Comment by rwjblue** [comment]
I think a more appropriate solution might be to reset / delete the values on the context that we do not want shared...

**Comment by Turbo87** [comment]
> Also, why is this targeting the older branch?

because it's a bugfix for an existing release, and `master` already has breaking changes (removal of chai) that would need a majpr version bump (or minor in this case since we're sub-1.0)

> I think a more appropriate solution might be to reset / delete the values on the context that we do not want shared...

From what I understand this is actually what we've been doing before. The module context was reset before each test and its values then assign to the mocha context.

That is actually my main point here, that we need to differentiate between test module context and mocha context. The mocha context, as you mentioned, is not being reset between tests, but the test module context that can be mutated by `set()` should be.

**Comment by Turbo87** [comment]
from Slack:

> [15:09] rwjblue: Regardless, I'm not blocking the revert for now

**Pull request merged**
