### PR TITLE
document first argument of setupAcceptanceTest

### PR DESCRIPTION
**Pull request by caseywatts**
since https://github.com/emberjs/ember-mocha/issues/131 isn't quite resolved yet - this change would have helped save me quite a bit of time just now :)
(I wouldn't mind if either this change is put in, or if #131 is actually finished/shipped instead)

### CODE REVIEW

**Comment by Turbo87** [comment]
I guess it can be annoying if the `master` branch does not document the latest release, but then again the same is true for Ember CLI and Ember.js themselves too. In the end you should always check with the documentation of the release that you're using, but I do agree that the current situation isn't great. I'll see if I can find some time to fix this mess.

**Comment by caseywatts** [comment]
That makes so much sense - and yet I've never thought to look up the README.md for the latest release (over master) before lol

Good advice :)

**Comment by caseywatts** [comment]
I just discovered the branch switcher has a `tags` tab - it's way easier than I'd expected too ✨

**Comment by Turbo87** [comment]
I've just released `v0.12.0`, which makes this PR obsolete. Thanks anyways! 👍

**Pull request closed without merging**
