### PR TITLE
CI: Publish tags to NPM

### LINKED ISSUE #99: CI: Publish tags for NPM and Bower automatically

### PR DESCRIPTION
**Pull request by Turbo87**
This PR will instruct TravisCI to automatically publish to NPM when tags are pushed to this repo.

@wifelette suggested to use the https://www.npmjs.com/~ember account, but since I don't have access to that account yet I've used my own for now.

Resolves #99 

/cc @rwjblue @nathanhammond @stefanpenner

### CODE REVIEW

**Comment by nathanhammond** [comment]
What if you tag something `foo`? How do you handle publishing to a different `dist-tag`?

**Comment by nathanhammond** [comment]
There is also https://www.npmjs.com/~emberjs

**Comment by nathanhammond** [comment]
(Seems fine to me, by the way, but I don't know what the opinions are of others.)

**Comment by Turbo87** [comment]
> rwjblue [21:12]  @tbieniek: I'm happy to let Travis publish

**Pull request merged**
