### PR TITLE
beforeRun, afterRun, beforeEachRun, afterEachRun

### PR DESCRIPTION
**Pull request by akatov**
needs #164 
alternative to #165

### CODE REVIEW

**Comment by Turbo87** [comment]
@akatov I am not convinced that we need these functions. It seems easy enough to just use `Ember.run()` inside of a `beforeEach()` hook if you want to use it instead of using `beforeEachRun()` which complicates the API of this project and makes it significantly harder to maintain.

**Comment by akatov** [comment]
fair enough, this makes sense.
What about at least exposing the `wrapMochaHookInEmberRun` function so consumers can define their own wrapped hooks should they wish to? I'd be happy to adjust this PR, or even open a new PR using the first commit on this branch with a unit test marked specifically to test this wrapping function...

**Comment by Turbo87** [comment]
> What about at least exposing the wrapMochaHookInEmberRun function so consumers can define their own wrapped hooks should they wish to?

as I mentioned above this increases the API surface of this project and the current way that we override these hooks is already brittle (think `beforeEach.skip()` or stuff like that) so I would prefer not to have that at all given how easy it is to just put `run(() => {...})` in the hooks.

**Comment by akatov** [comment]
fair enough, closing this and #165 then

**Pull request closed without merging**
